### ISSUE TITLE
🐛 Cannot skip intro

### ISSUE THREAD

**Issue by AdrKacz** [AdrKacz/scaling-broccoli#37]
### Describe the bug
Pas possible de cliquer pour skip l'intro, le template se remt toujours mal à jour, il faut overwrite le code pour le calmer.

Faire une issue aussi chez le owner.

**Comment by AdrKacz** [comment]
Issue create in main template to keep track: https://github.com/duongvituan/godot-awesome-splash/issues/13

**Comment by AdrKacz** [comment]
Second issue, only skip on MouseInput, should be ALL input (well, in our case mouse doesn't make sense as it is a mobile game)

**Comment by AdrKacz** [comment]
Replaced in module

```
func _skip_awe_splash_by_event(event) -> bool:
	return event is InputEventMouseButton \
			and event.pressed \
			and event.button_index == 1
```

By

```
func _skip_awe_splash_by_event(event) -> bool:
	return event.is_pressed() \
		and ((event is InputEventMouseButton and event.button_index == 1) \
		or (event is InputEventScreenTouch))
```

**Comment by AdrKacz** [comment]
Cannot reproduce the `random reset` bug, maybe just a problem on my config that disparear after reset, while keep and eye on that and close the other issue if I don't see it again

**Comment by duongvituan** [comment]
> Replaced in module
> 
> ```
> func _skip_awe_splash_by_event(event) -> bool:
> 	return event is InputEventMouseButton \
> 			and event.pressed \
> 			and event.button_index == 1
> ```
> 
> By
> 
> ```
> func _skip_awe_splash_by_event(event) -> bool:
> 	return event.is_pressed() \
> 		and ((event is InputEventMouseButton and event.button_index == 1) \
> 		or (event is InputEventScreenTouch))
> ```

@AdrKacz 
The above code is very reasonable in case of running on mobile app,
can you make 1 pull to splash repo?
Thank you, :D
